events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;

        location /api/operaciones {
            proxy_pass http://servicio-operaciones:8002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/vehiculos {
            proxy_pass http://servicio-vehiculos:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
