server:
  port: 8081

spring:
  application:
    name: servicio-vehiculos
  datasource:
    url: jdbc:mysql://mysql:3306/alquiler?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: alquiler
    password: alquiler
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
